fixtures:
  repositories:
    'keystone': 'git://github.com/stackforge/puppet-keystone.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'mysql':
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: 'origin/0.x'
  symlinks:
    'ironic': "#{source_dir}"
